resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/tags/v0.1.0-alpha.2
      endpoint: andraantariksa

stages:
  - stage: test
    displayName: "Tests"
    jobs:
    - template: ci/jobs/cargo-test.yaml@rust_pipelines
      parameters:
        test-flags:
          nocapture: true
        job_strategy:
          matrix:
            Linux:
              vmImage: ubuntu-16.04
            Windows:
              vmImage: vs2017-win2016

  - stage: build
    displayName: "Builds"
    dependsOn:
    - test
    jobs:
    - template: ci/jobs/cargo-build.yml@rust_pipelines 
      parameters:
        artifactName: target
        test-flags:
          nocapture: true
        builds:
        - target: x86_64-unknown-linux-gnu 
          name: x86_64_unknown_linux_gnu
          pre-steps: []
        - target: x86_64-pc-windows-msvc
          name: x86_64_pc_windows_msvc
          pre-steps: []
